---
chdir: /var/www/igakuten-app/current
environment: production
port: 3001
timeout: 30
log: /var/www/igakuten-app/shared/log/thin.log
pid: /var/www/igakuten-app/shared/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
wait: 30
servers: 1
daemonize: true
